version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}exampleapplication
    build:
      context: .
      dockerfile: ExampleApplication/Dockerfile

  client:
    image: client
    build: 
      context: ./example-client
      dockerfile: Dockerfile

  proxy: 
    image: nginx:mainline